### ISSUE TITLE
error when trying to write v1.5 image file

### ISSUE THREAD

**Issue by dadjeanious** [wednesdayayay/Scrawl#1]
I've downloaded the image .zip file a couple different times from the download link provided.

((https://drive.google.com/open?id=1ep0ZNawBRCll6pyFvFSpVqMtxO2fa4qM))

I keep getting the error below when I try to unzip with the windows unzip utility. Please help? Thank you!

![scrawl unzip error](https://user-images.githubusercontent.com/61942005/77256076-89d73080-6c31-11ea-91cf-697df2f7d769.PNG)

**Comment by dadjeanious** [comment]
never mind, I'm an idiot. :) no need to unzip an .iso file just burn it to the sd card. balena etcher gave me an error about a zipped file originally though but now it seems to be working...

**Comment by dadjeanious** [comment]
OK, maybe I'm not an idiot... Etcher doesn't finish writing the image to the sd card... can you check image please?
![image](https://user-images.githubusercontent.com/61942005/77259362-72ef0900-6c46-11ea-9f28-563cfecaaacf.png)

**Comment by dadjeanious** [comment]
it's confirmed, I'm an idiot! the zipped image file worked when I unzipped it and etched it properly.

**Comment by wednesdayayay** [comment]
haha sorry about any confusion 
it looks like you've got it sorted now hopefully
but I have recently uploaded an additional uncompressed image alongside the compressed image
mostly it seems like windows users were having issues with the compressed version
I know before uploading the image it worked great it is running on both my machines currently
